import { Product, Category } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-mobiles', name: 'Mobiles', slug: 'mobiles', description: 'Flagship smartphones, 5G devices & accessories', image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80' },
  { id: 'cat-laptops', name: 'Laptops', slug: 'laptops', description: 'Ultra-thin ultrabooks, gaming laptops & workstations', image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80' },
  { id: 'cat-electronics', name: 'Electronics', slug: 'electronics', description: '4K Smart TVs, wireless audio, cameras & drones', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80' },
  { id: 'cat-fashion', name: 'Fashion', slug: 'fashion', description: 'Designer denim, jackets, streetwear & apparel', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&q=80' },
  { id: 'cat-shoes', name: 'Shoes', slug: 'shoes', description: 'Performance running kicks, sneakers & boots', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80' },
  { id: 'cat-watches', name: 'Watches', slug: 'watches', description: 'Automatic timepieces & retina smartwatches', image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80' },
  { id: 'cat-grocery', name: 'Grocery', slug: 'grocery', description: 'Organic produce, gourmet coffee & pantry items', image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80' },
  { id: 'cat-home-kitchen', name: 'Home & Kitchen', slug: 'home-kitchen', description: 'Smart appliances, cookware & minimalist decor', image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80' },
  { id: 'cat-beauty', name: 'Beauty', slug: 'beauty', description: 'Luxury skincare, fragrances & cosmetics', image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80' },
  { id: 'cat-books', name: 'Books', slug: 'books', description: 'Bestselling novels, tech guides & biographies', image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80' },
  { id: 'cat-toys', name: 'Toys', slug: 'toys', description: 'STEM kits, RC drones, action figures & games', image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&q=80' },
  { id: 'cat-sports', name: 'Sports', slug: 'sports', description: 'Fitness gear, yoga mats, dumbbells & cycles', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80' },
];

export const MOCK_PRODUCTS: Product[] = [
  // ── 1. MOBILES ─────────────────────────────────────────────────────────────
  {
    id: 'mob-1',
    name: 'Apple iPhone 15 Pro Max 256GB',
    slug: 'apple-iphone-15-pro-max-256gb',
    description: 'Titanium design, A17 Pro chip, 48MP camera system with 5x Telephoto zoom.',
    price: 149900,
    discountPrice: 134900,
    sku: 'SKU-MOB-01',
    stock: 25,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80'],
    rating: 4.9,
    reviewCount: 342,
    isFeatured: true,
    category: { id: 'cat-mobiles', name: 'Mobiles', slug: 'mobiles' },
    brand: { id: 'b-apple', name: 'Apple', slug: 'apple' },
  },
  {
    id: 'mob-2',
    name: 'Samsung Galaxy S24 Ultra 5G 512GB',
    slug: 'samsung-galaxy-s24-ultra-5g',
    description: 'Galaxy AI, Titanium Armor, Built-in S Pen, 200MP Quad Telephoto Camera.',
    price: 139999,
    discountPrice: 129999,
    sku: 'SKU-MOB-02',
    stock: 18,
    images: ['https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80'],
    rating: 4.8,
    reviewCount: 280,
    isFeatured: true,
    category: { id: 'cat-mobiles', name: 'Mobiles', slug: 'mobiles' },
    brand: { id: 'b-samsung', name: 'Samsung', slug: 'samsung' },
  },
  {
    id: 'mob-3',
    name: 'OnePlus 12 5G (Silky Black 16GB RAM)',
    slug: 'oneplus-12-5g-silky-black',
    description: 'Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera, 100W SUPERVOOC charging.',
    price: 69999,
    discountPrice: 64999,
    sku: 'SKU-MOB-03',
    stock: 40,
    images: ['https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&q=80'],
    rating: 4.7,
    reviewCount: 195,
    isFeatured: false,
    category: { id: 'cat-mobiles', name: 'Mobiles', slug: 'mobiles' },
    brand: { id: 'b-oneplus', name: 'OnePlus', slug: 'oneplus' },
  },
  {
    id: 'mob-4',
    name: 'Google Pixel 8 Pro 128GB Bay Blue',
    slug: 'google-pixel-8-pro-128gb',
    description: 'Google Tensor G3 chip, AI Magic Eraser, Best Take, Pro Controls.',
    price: 93999,
    discountPrice: 84999,
    sku: 'SKU-MOB-04',
    stock: 15,
    images: ['https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&q=80'],
    rating: 4.6,
    reviewCount: 142,
    isFeatured: false,
    category: { id: 'cat-mobiles', name: 'Mobiles', slug: 'mobiles' },
    brand: { id: 'b-google', name: 'Google', slug: 'google' },
  },

  // ── 2. LAPTOPS ────────────────────────────────────────────────────────────
  {
    id: 'lap-1',
    name: 'Apple MacBook Pro 14" M3 Pro 18GB/512GB',
    slug: 'apple-macbook-pro-14-m3-pro',
    description: 'Liquid Retina XDR display, 18-core GPU, up to 18 hours battery life.',
    price: 199900,
    discountPrice: 184900,
    sku: 'SKU-LAP-01',
    stock: 12,
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80'],
    rating: 4.9,
    reviewCount: 210,
    isFeatured: true,
    category: { id: 'cat-laptops', name: 'Laptops', slug: 'laptops' },
    brand: { id: 'b-apple', name: 'Apple', slug: 'apple' },
  },
  {
    id: 'lap-2',
    name: 'Dell XPS 15 OLED Touch Intel i9 32GB',
    slug: 'dell-xps-15-oled-touch-i9',
    description: '3.5K OLED display, RTX 4060 GPU, CNC machined aluminum chassis.',
    price: 199990,
    discountPrice: 184990,
    sku: 'SKU-LAP-02',
    stock: 8,
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80'],
    rating: 4.8,
    reviewCount: 175,
    isFeatured: true,
    category: { id: 'cat-laptops', name: 'Laptops', slug: 'laptops' },
    brand: { id: 'b-dell', name: 'Dell', slug: 'dell' },
  },
  {
    id: 'lap-3',
    name: 'Asus ROG Zephyrus G16 Gaming Laptop',
    slug: 'asus-rog-zephyrus-g16-gaming',
    description: 'Intel Core Ultra 9, RTX 4070 8GB, 240Hz Nebula Display.',
    price: 179990,
    discountPrice: 169990,
    sku: 'SKU-LAP-03',
    stock: 15,
    images: ['https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80'],
    rating: 4.7,
    reviewCount: 160,
    isFeatured: false,
    category: { id: 'cat-laptops', name: 'Laptops', slug: 'laptops' },
    brand: { id: 'b-asus', name: 'Asus', slug: 'asus' },
  },

  // ── 3. ELECTRONICS ─────────────────────────────────────────────────────────
  {
    id: 'elec-1',
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling',
    slug: 'sony-wh-1000xm5-wireless-headphones',
    description: 'Industry leading noise cancelling, 30hr battery life, crystal clear hands-free calling.',
    price: 34990,
    discountPrice: 29990,
    sku: 'SKU-ELEC-01',
    stock: 50,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80'],
    rating: 4.9,
    reviewCount: 420,
    isFeatured: true,
    category: { id: 'cat-electronics', name: 'Electronics', slug: 'electronics' },
    brand: { id: 'b-sony', name: 'Sony', slug: 'sony' },
  },
  {
    id: 'elec-2',
    name: 'Samsung 65" QLED 4K Smart TV',
    slug: 'samsung-65-qled-4k-smart-tv',
    description: 'Quantum Dot 100% color volume, Motion Xcelerator 120Hz, SolarCell remote.',
    price: 124990,
    discountPrice: 109990,
    sku: 'SKU-ELEC-02',
    stock: 10,
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f4e5f1?w=800&q=80'],
    rating: 4.8,
    reviewCount: 190,
    isFeatured: true,
    category: { id: 'cat-electronics', name: 'Electronics', slug: 'electronics' },
    brand: { id: 'b-samsung', name: 'Samsung', slug: 'samsung' },
  },
  {
    id: 'elec-3',
    name: 'Bose QuietComfort Ultra Headphones',
    slug: 'bose-quietcomfort-ultra-headphones',
    description: 'Immersive Audio with Spatial Sound, CustomTune technology, 24-hour battery.',
    price: 35990,
    discountPrice: 34990,
    sku: 'SKU-ELEC-03',
    stock: 30,
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80'],
    rating: 4.7,
    reviewCount: 230,
    isFeatured: false,
    category: { id: 'cat-electronics', name: 'Electronics', slug: 'electronics' },
    brand: { id: 'b-bose', name: 'Bose', slug: 'bose' },
  },

  // ── 4. FASHION ─────────────────────────────────────────────────────────────
  {
    id: 'fash-1',
    name: "Levi's Original Denim Trucker Jacket",
    slug: 'levis-original-denim-trucker-jacket',
    description: 'Classic fit premium 100% cotton denim jacket with branded metal shank buttons.',
    price: 5499,
    discountPrice: 4499,
    sku: 'SKU-FASH-01',
    stock: 45,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80'],
    rating: 4.6,
    reviewCount: 145,
    isFeatured: true,
    category: { id: 'cat-fashion', name: 'Fashion', slug: 'fashion' },
    brand: { id: 'b-levis', name: "Levi's", slug: 'levis' },
  },
  {
    id: 'fash-2',
    name: 'Zara Premium Slim-Fit Wool Blazer',
    slug: 'zara-premium-slim-fit-wool-blazer',
    description: 'Tailored notched lapel suit blazer crafted from fine Italian wool blend.',
    price: 8990,
    discountPrice: 7990,
    sku: 'SKU-FASH-02',
    stock: 20,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80'],
    rating: 4.7,
    reviewCount: 110,
    isFeatured: true,
    category: { id: 'cat-fashion', name: 'Fashion', slug: 'fashion' },
    brand: { id: 'b-zara', name: 'Zara', slug: 'zara' },
  },
  {
    id: 'fash-3',
    name: 'Nike Sportswear Tech Fleece Hoodie',
    slug: 'nike-sportswear-tech-fleece-hoodie',
    description: 'Lightweight warmth Tech Fleece fabric with zippered sleeve pocket.',
    price: 7995,
    discountPrice: 6995,
    sku: 'SKU-FASH-03',
    stock: 35,
    images: ['https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80'],
    rating: 4.8,
    reviewCount: 290,
    isFeatured: false,
    category: { id: 'cat-fashion', name: 'Fashion', slug: 'fashion' },
    brand: { id: 'b-nike', name: 'Nike', slug: 'nike' },
  },

  // ── 5. SHOES ───────────────────────────────────────────────────────────────
  {
    id: 'shoe-1',
    name: 'Nike Air Jordan 1 Retro High OG Chicago',
    slug: 'nike-air-jordan-1-retro-high-og',
    description: 'Iconic high-top sneaker with premium full-grain leather and Air-Sole cushioning.',
    price: 18995,
    discountPrice: 16995,
    sku: 'SKU-SHOE-01',
    stock: 30,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'],
    rating: 4.9,
    reviewCount: 512,
    isFeatured: true,
    category: { id: 'cat-shoes', name: 'Shoes', slug: 'shoes' },
    brand: { id: 'b-nike', name: 'Nike', slug: 'nike' },
  },
  {
    id: 'shoe-2',
    name: 'Adidas Ultraboost Light Running Shoes',
    slug: 'adidas-ultraboost-light-running-shoes',
    description: 'Lightest Boost midsole technology for maximum energy return on long runs.',
    price: 19999,
    discountPrice: 18999,
    sku: 'SKU-SHOE-02',
    stock: 25,
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80'],
    rating: 4.8,
    reviewCount: 380,
    isFeatured: true,
    category: { id: 'cat-shoes', name: 'Shoes', slug: 'shoes' },
    brand: { id: 'b-adidas', name: 'Adidas', slug: 'adidas' },
  },
  {
    id: 'shoe-3',
    name: 'Puma Velocity Nitro 3 Running Kicks',
    slug: 'puma-velocity-nitro-3-running-kicks',
    description: 'NITROFOAM cushioning with PUMAGRIP durable rubber outsole traction.',
    price: 12999,
    discountPrice: 11999,
    sku: 'SKU-SHOE-03',
    stock: 40,
    images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80'],
    rating: 4.7,
    reviewCount: 220,
    isFeatured: false,
    category: { id: 'cat-shoes', name: 'Shoes', slug: 'shoes' },
    brand: { id: 'b-puma', name: 'Puma', slug: 'puma' },
  },

  // ── 6. WATCHES ─────────────────────────────────────────────────────────────
  {
    id: 'wat-1',
    name: 'Seiko Presage Automatic Mechanical Watch',
    slug: 'seiko-presage-automatic-mechanical-watch',
    description: 'Japanese 4R35 automatic caliber, Sapphire crystal glass, stainless steel bracelet.',
    price: 42000,
    discountPrice: 38500,
    sku: 'SKU-WAT-01',
    stock: 14,
    images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80'],
    rating: 4.9,
    reviewCount: 185,
    isFeatured: true,
    category: { id: 'cat-watches', name: 'Watches', slug: 'watches' },
    brand: { id: 'b-seiko', name: 'Seiko', slug: 'seiko' },
  },
  {
    id: 'wat-2',
    name: 'Apple Watch Ultra 2 GPS + Cellular 49mm',
    slug: 'apple-watch-ultra-2-gps-cellular',
    description: 'Titanium case, 3000-nit display, Dual-frequency GPS, 36-hour battery life.',
    price: 89900,
    discountPrice: 84900,
    sku: 'SKU-WAT-02',
    stock: 18,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80'],
    rating: 4.9,
    reviewCount: 410,
    isFeatured: true,
    category: { id: 'cat-watches', name: 'Watches', slug: 'watches' },
    brand: { id: 'b-apple', name: 'Apple', slug: 'apple' },
  },
  {
    id: 'wat-3',
    name: 'Fossil Gen 6 Touchscreen Smartwatch',
    slug: 'fossil-gen-6-touchscreen-smartwatch',
    description: 'Snapdragon Wear 4100+, Wear OS, SpO2 sensor, fast charging to 80% in 30 mins.',
    price: 24995,
    discountPrice: 19995,
    sku: 'SKU-WAT-03',
    stock: 22,
    images: ['https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80'],
    rating: 4.6,
    reviewCount: 130,
    isFeatured: false,
    category: { id: 'cat-watches', name: 'Watches', slug: 'watches' },
    brand: { id: 'b-fossil', name: 'Fossil', slug: 'fossil' },
  },

  // ── 7. GROCERY ─────────────────────────────────────────────────────────────
  {
    id: 'groc-1',
    name: 'Tata Tea Gold Premium Assam Blend 1kg',
    slug: 'tata-tea-gold-premium-assam-blend-1kg',
    description: '100% pure Assam tea leaves blended with long leaf teas for rich aroma & taste.',
    price: 699,
    discountPrice: 599,
    sku: 'SKU-GROC-01',
    stock: 100,
    images: ['https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80'],
    rating: 4.8,
    reviewCount: 620,
    isFeatured: true,
    category: { id: 'cat-grocery', name: 'Grocery', slug: 'grocery' },
    brand: { id: 'b-tata', name: 'Tata', slug: 'tata' },
  },
  {
    id: 'groc-2',
    name: 'Nescafe Gold Blend Freeze Dried Coffee 200g',
    slug: 'nescafe-gold-blend-coffee-200g',
    description: 'Crafted with Arabica coffee beans for a smooth, rich gourmet cup of coffee.',
    price: 1099,
    discountPrice: 899,
    sku: 'SKU-GROC-02',
    stock: 80,
    images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80'],
    rating: 4.7,
    reviewCount: 450,
    isFeatured: true,
    category: { id: 'cat-grocery', name: 'Grocery', slug: 'grocery' },
    brand: { id: 'b-nescafe', name: 'Nescafe', slug: 'nescafe' },
  },

  // ── 8. HOME & KITCHEN ──────────────────────────────────────────────────────
  {
    id: 'hk-1',
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker',
    slug: 'instant-pot-duo-7-in-1-electric-cooker',
    description: 'Replaces 7 kitchen appliances: pressure cooker, slow cooker, rice cooker, steamer.',
    price: 11990,
    discountPrice: 9990,
    sku: 'SKU-HK-01',
    stock: 25,
    images: ['https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80'],
    rating: 4.9,
    reviewCount: 380,
    isFeatured: true,
    category: { id: 'cat-home-kitchen', name: 'Home & Kitchen', slug: 'home-kitchen' },
    brand: { id: 'b-instantpot', name: 'Instant Pot', slug: 'instantpot' },
  },
  {
    id: 'hk-2',
    name: 'Philips Digital Air Fryer XXL 1.4kg Capacity',
    slug: 'philips-digital-air-fryer-xxl',
    description: 'Rapid CombiAir technology, 90% less fat frying, NutriU app connected recipes.',
    price: 17990,
    discountPrice: 14990,
    sku: 'SKU-HK-02',
    stock: 18,
    images: ['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&q=80'],
    rating: 4.8,
    reviewCount: 290,
    isFeatured: true,
    category: { id: 'cat-home-kitchen', name: 'Home & Kitchen', slug: 'home-kitchen' },
    brand: { id: 'b-philips', name: 'Philips', slug: 'philips' },
  },

  // ── 9. BEAUTY ──────────────────────────────────────────────────────────────
  {
    id: 'beau-1',
    name: 'Estée Lauder Advanced Night Repair Serum 50ml',
    slug: 'estee-lauder-advanced-night-repair-serum',
    description: 'Patented Chronolux Power Signal Technology for deep fast night renewal.',
    price: 9900,
    discountPrice: 8900,
    sku: 'SKU-BEAU-01',
    stock: 35,
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80'],
    rating: 4.9,
    reviewCount: 480,
    isFeatured: true,
    category: { id: 'cat-beauty', name: 'Beauty', slug: 'beauty' },
    brand: { id: 'b-esteelauder', name: 'Estée Lauder', slug: 'esteelauder' },
  },
  {
    id: 'beau-2',
    name: 'MAC Matte Lipstick Ruby Woo Iconic Red',
    slug: 'mac-matte-lipstick-ruby-woo',
    description: 'The world famous iconic matte blue-red lipstick with ultra-intense payoff.',
    price: 2200,
    discountPrice: 1950,
    sku: 'SKU-BEAU-02',
    stock: 60,
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80'],
    rating: 4.8,
    reviewCount: 590,
    isFeatured: true,
    category: { id: 'cat-beauty', name: 'Beauty', slug: 'beauty' },
    brand: { id: 'b-mac', name: 'MAC', slug: 'mac' },
  },

  // ── 10. BOOKS ──────────────────────────────────────────────────────────────
  {
    id: 'book-1',
    name: 'Atomic Habits by James Clear (Hardcover)',
    slug: 'atomic-habits-james-clear-hardcover',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones. Over 15 Million Copies Sold.',
    price: 699,
    discountPrice: 499,
    sku: 'SKU-BOOK-01',
    stock: 120,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80'],
    rating: 4.9,
    reviewCount: 1420,
    isFeatured: true,
    category: { id: 'cat-books', name: 'Books', slug: 'books' },
    brand: { id: 'b-penguin', name: 'Penguin', slug: 'penguin' },
  },
  {
    id: 'book-2',
    name: 'The Psychology of Money by Morgan Housel',
    slug: 'the-psychology-of-money-morgan-housel',
    description: 'Timeless lessons on wealth, greed, and happiness doing well with money.',
    price: 499,
    discountPrice: 399,
    sku: 'SKU-BOOK-02',
    stock: 90,
    images: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80'],
    rating: 4.8,
    reviewCount: 980,
    isFeatured: true,
    category: { id: 'cat-books', name: 'Books', slug: 'books' },
    brand: { id: 'b-harriman', name: 'Harriman House', slug: 'harriman' },
  },

  // ── 11. TOYS ───────────────────────────────────────────────────────────────
  {
    id: 'toy-1',
    name: 'LEGO Star Wars Millennium Falcon 75257 Kit',
    slug: 'lego-star-wars-millennium-falcon-75257',
    description: '1,351 pieces starship model with Finn, Chewbacca, Lando Calrissian minifigures.',
    price: 16999,
    discountPrice: 14999,
    sku: 'SKU-TOY-01',
    stock: 15,
    images: ['https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&q=80'],
    rating: 4.9,
    reviewCount: 310,
    isFeatured: true,
    category: { id: 'cat-toys', name: 'Toys', slug: 'toys' },
    brand: { id: 'b-lego', name: 'LEGO', slug: 'lego' },
  },
  {
    id: 'toy-2',
    name: 'Hot Wheels 10-Car Pack Die-Cast Vehicles',
    slug: 'hot-wheels-10-car-pack-die-cast',
    description: '1:64 scale die-cast sports vehicles featuring iconic realistic racing designs.',
    price: 1499,
    discountPrice: 1299,
    sku: 'SKU-TOY-02',
    stock: 50,
    images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&q=80'],
    rating: 4.8,
    reviewCount: 450,
    isFeatured: true,
    category: { id: 'cat-toys', name: 'Toys', slug: 'toys' },
    brand: { id: 'b-mattel', name: 'Mattel', slug: 'mattel' },
  },

  // ── 12. SPORTS ─────────────────────────────────────────────────────────────
  {
    id: 'spt-1',
    name: 'Cosco Rubber Hex Dumbbells Set 20kg Pair',
    slug: 'cosco-rubber-hex-dumbbells-set-20kg',
    description: 'Heavy duty hex dumbbells with anti-roll design and ergonomic chrome steel grip.',
    price: 4999,
    discountPrice: 3999,
    sku: 'SKU-SPT-01',
    stock: 30,
    images: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80'],
    rating: 4.8,
    reviewCount: 240,
    isFeatured: true,
    category: { id: 'cat-sports', name: 'Sports', slug: 'sports' },
    brand: { id: 'b-cosco', name: 'Cosco', slug: 'cosco' },
  },
  {
    id: 'spt-2',
    name: 'Decathlon Domyos Non-Slip Yoga Mat 8mm',
    slug: 'decathlon-domyos-non-slip-yoga-mat-8mm',
    description: 'High-density TPE cushioning for maximum joint comfort during yoga & workouts.',
    price: 1899,
    discountPrice: 1499,
    sku: 'SKU-SPT-02',
    stock: 60,
    images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80'],
    rating: 4.7,
    reviewCount: 380,
    isFeatured: true,
    category: { id: 'cat-sports', name: 'Sports', slug: 'sports' },
    brand: { id: 'b-decathlon', name: 'Decathlon', slug: 'decathlon' },
  },
];

export async function fetchProducts(query?: string, categorySlug?: string): Promise<Product[]> {
  let filtered = [...MOCK_PRODUCTS];

  if (categorySlug && categorySlug !== 'all') {
    filtered = filtered.filter(p => p.category.slug === categorySlug);
  }

  if (query && query.trim() !== '') {
    const q = query.toLowerCase().trim();
    filtered = filtered.filter(
      p =>
        p.name.toLowerCase().includes(q) ||
        p.description.toLowerCase().includes(q) ||
        p.category.name.toLowerCase().includes(q) ||
        p.category.slug.toLowerCase().includes(q) ||
        p.brand?.name.toLowerCase().includes(q)
    );
  }

  return filtered;
}
